# Generated by Django 2.2.3 on 2019-08-22 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SolvingAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('cost', models.IntegerField()),
                ('grade', models.IntegerField(blank=True, null=True, validators=[
                 django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(blank=True, choices=[
                 ('S', 'Solving'), ('C', 'Checking'), ('SD', 'Solved')], default='S', max_length=2)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('score', models.FloatField(default=500)),
                ('problems', models.ManyToManyField(related_name='teams', related_query_name='team',
                                                    through='contest.SolvingAttempt', to='contest.Problem')),
            ],
            options={
                'ordering': ('-score',),
            },
        ),
        migrations.AddField(
            model_name='solvingattempt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Team'),
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worth', models.FloatField(blank=True, null=True)),
                ('pending', models.BooleanField(blank=True, default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Problem')),
                ('requested_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='duel_requests', related_query_name='duel_request', to='contest.Team')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                         related_name='duels', related_query_name='duel', to='contest.Team')),
                ('winner', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='duel_wins', related_query_name='win_duel', to='contest.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='solvingattempt',
            unique_together={('team', 'problem')},
        ),
    ]
