# Generated by Django 2.2.3 on 2019-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='worth',
        ),
        migrations.AddField(
            model_name='duel',
            name='type',
            field=models.CharField(choices=[('1', 'Type1 8%'), ('2', 'Type2 12%'), ('3', 'Type3 16%')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('P', 'Problem'), ('D', 'Duel')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
