# Generated by Django 2.2.3 on 2019-08-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='req_returned',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='to_returned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
