# Generated by Django 2.2.3 on 2019-08-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='extra',
            field=models.TextField(null=True),
        ),
    ]
