# Generated by Django 2.2.4 on 2019-08-29 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_transaction_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvingattempt',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
